### ISSUE TITLE
bare return breaks things

### ISSUE THREAD

**Issue by davidbau** [yjerem/pencil-tracer#1]
The following causes an uncaught exception instead of doing any thinking:

http://david.pencilcode.net/edit/bug/return

```
think = ->
  return
think()
```

**Comment by davidbau** [comment]
Details - the exception is:

```
Could not compile  after instrumenting: SyntaxError: cannot use a pure statement in an expression
```

**Comment by yjerem** [comment]
I forgot to test bare returns! Thanks, I added it to the tests.

Recently I replaced all the return-manipulating code with a much simpler try..finally strategy for detecting enter and leave events, and this bug disappeared with those changes.
